server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: springboot-project
  datasource:
    url: jdbc:mysql://localhost:3306/person?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    web: trace
    org:
      hibernate:
        SQL: debug
      springframework:
        boot:
          autoconfigure=ERROR:
        web: trace

# swagger-ui custom path
springdoc:
  swagger-ui:
    path=/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus